### ISSUE TITLE
How to integrate Logify with Postsharp logging

### ISSUE THREAD

**Issue by noufionline** [DevExpress/Logify.Alert.Clients#1]
Hi There,
I am using Postsharp 5.0 Loggin with Serilog in my application (c# prism wpf application). As per your documentation, I have given the configuration, Since the logging is done through postsharp the logify is not getting notified.

Could you please help me on this please?

**Comment by Mirimon** [comment]
Hi,

If you are using Logify integration with Serilog, Logify sends reports only on the Error and Fatal logs, and you need to put an Exception object into these logs. Please refer to the following help article, which describes this integration in greater detail: [Plugin for Serilog](https://logify.devexpress.com/Alert/Documentation/Send/IntegrationWithLogSystems/Serilog) Additionally, you can include the last logs into a report using an approach from the following documentation page: [Include Preceding Logs into a Report](https://logify.devexpress.com/Alert/Documentation/HowTo/SendLogsWithReport)
 
Feel free to contact us if you need additional information.

Thanks
Alex

**Comment by noufionline** [comment]
I want to use Logify where Postsharp loggin is enabled with Serilog as backend. Unfortunately Its not working.

`
Log.Logger = new LoggerConfiguration()
            .WriteTo.Seq("http://localhost:5341").MinimumLevel.Error()
            .WriteTo.Console(LogEventLevel.Error)
            .WriteTo.LogifyAlert()
            .ReadFrom.AppSettings()
            .CreateLogger();
`

`LoggingServices.DefaultBackend = new SerilogLoggingBackend();`

so everytime when SeriLog logs error through Postsharp I want Logify to get the errors. 

How can I achieve this?

**Comment by Mirimon** [comment]
I have reproduced this behavior and forwarded this issue to our R&D team. They will research it and do their best to fix it.

**Comment by Mirimon** [comment]
Hi,

Thanks you for your patience. The cause of this issue is that a LogifyAlert client requires initialization before using by Serilog. You can write just:
`LogifyAlert client = LogifyAlert.Instance;`

before creating LoggerConfiguration. We have updated our documentation regarding this: [Logify Alert for Serilog](https://github.com/DevExpress/Logify.Alert.Clients/tree/develop/dotnet/Logify.Alert.Serilog)

Thanks
Alex

**Comment by noufionline** [comment]
Thanks.

But I don't see any usage of client variable anywhere in your code? Is that just part of instantiation?

`LogifyAlert client = LogifyAlert.Instance;`

**Comment by Mirimon** [comment]
Hi,

Yes, this code is required only for initialization. We will discuss including a static method like "Init" for this in the future.

Thanks
Alex
