### ISSUE TITLE
How to use Logify with ASP.NET Core 2.0

### ISSUE THREAD

**Issue by noufionline** [DevExpress/Logify.Alert.Clients#2]

**Comment by rkolesnikovDX** [comment]
Hi,
I've added a note to the following article describing how to use Logify with the ASP.NET Core 2.0 -https://github.com/DevExpress/Logify.Alert.Clients/blob/develop/dotnet/Logify.Alert.NetCore.Web/readme_netcore_2_0.md

Feel free to contact us if you need additional information.
 
Thanks,
Roman
