### ISSUE TITLE
read error

### ISSUE THREAD

**Issue by ghost1372** [DevExpress/Logify.Alert.Clients#5]
hi is there any way to read collected error? i want read error data (title, body,...) when error occured and store it to some file. i know that i can use offlineMethod to store data but i need to another way to access error details

**Comment by Mirimon** [comment]
Hi,

If it is enough for you to get only information about the exception and you are using .NET, you can subscribe to the [BeforeReportException](https://logify.devexpress.com/Alert/Documentation/Send/ApiReference/WinWebWpf#BeforeReportException) event. The Exception object will be available in its event args.

Thanks
Alex
